# Copyright (C) 2024 Roberto Rossini <roberros@uio.no>
# SPDX-License-Identifier: MIT

name: macOS CI

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/macos-ci.yml"
      - ".github/workflows/build-conan-deps.yml"
      - "CMakeLists.txt"
      - "conanfile.py"
      - "main.cpp"

  pull_request:
    paths:
      - ".github/workflows/macos-ci.yml"
      - ".github/workflows/build-conan-deps.yml"
      - "CMakeLists.txt"
      - "conanfile.py"
      - "main.cpp"

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  matrix-factory:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-result.outputs.result }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.after }}

      - name: Detect CI type
        id: ci-type
        run: |
          if git log --format=%B -n 1 ${{ github.event.after }} | grep -qF '[ci full]'; then
            echo "type=full" | tee -a "$GITHUB_OUTPUT"
          else
            echo "type=short" | tee -a "$GITHUB_OUTPUT"
          fi

      - name: Generate matrix
        uses: actions/github-script@v7
        id: set-result
        with:
          script: |
            // Documentation
            // https://docs.github.com/en/actions/learn-github-actions/contexts#fromjson
            // https://github.com/actions/runner/issues/982#issuecomment-809360765

            var includes = []

            includes.push({ compiler_name: 'apple-clang', compiler_version: '14', os: 'macos-12', conan: '2.4.*', cmake: '3.29.*', build_type: 'Release', developer_mode: 'OFF' })
            includes.push({ compiler_name: 'apple-clang', compiler_version: '15', os: 'macos-13', conan: '2.4.*', cmake: '3.29.*', build_type: 'Release', developer_mode: 'OFF' })
            includes.push({ compiler_name: 'apple-clang', compiler_version: '15', os: 'macos-14', conan: '2.4.*', cmake: '3.29.*', build_type: 'Release', developer_mode: 'OFF' })
            includes.push({ compiler_name: 'apple-clang', compiler_version: '15', os: 'macos-13', conan: '2.4.*', cmake: '3.29.*', build_type: 'Debug',   developer_mode: 'OFF' })
            includes.push({ compiler_name: 'apple-clang', compiler_version: '15', os: 'macos-14', conan: '2.4.*', cmake: '3.29.*', build_type: 'Debug',   developer_mode: 'OFF' })

            return { include: includes }

  build-conan-deps-x86:
    name: Build Conan deps
    uses: robomics/gha-devel/.github/workflows/build-conan-deps.yml@main
    with:
      os: macos-12

  build-conan-deps-arm64:
    name: Build Conan deps
    uses: robomics/gha-devel/.github/workflows/build-conan-deps.yml@main
    with:
      os: macos-14

  build-project:
    name: Build project
    needs:
      - matrix-factory
      - build-conan-deps-x86
      - build-conan-deps-arm64
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.matrix-factory.outputs.matrix) }}
    runs-on: ${{ matrix.os }}

    env:
      CCACHE_DIR: "${{ github.workspace }}/ccache-cache"
      CCACHE_COMPILERCHECK: "content"
      CCACHE_COMPRESSLEVEL: "1"
      CCACHE_MAXSIZE: "250M"
      CONAN_HOME: "${{ github.workspace }}/.conan2"
      HOMEBREW_NO_AUTO_UPDATE: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Generate requirements.txt for pip
        run: |
          echo 'conan==${{ matrix.conan }}' > requirements.txt
          echo 'cmake==${{ matrix.cmake }}' >> requirements.txt

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Detect number available CPUs
        run: |
          ncpus=$(python -c 'import multiprocessing as mp; print(mp.cpu_count())')

          echo "NPROC=$ncpus" >> $GITHUB_ENV
          echo "CMAKE_BUILD_PARALLEL_LEVEL=$ncpus" >> $GITHUB_ENV
          echo "CTEST_PARALLEL_LEVEL=$ncpus" >> $GITHUB_ENV

      - name: Install build deps
        run: |
          pip install -r requirements.txt
          brew install ccache

      - name: Generate cache key
        id: cache-key
        run: |
          set -u

          os="${{ matrix.os }}"
          compiler="${{ matrix.compiler_name }}"
          compiler_version="${{ matrix.compiler_version }}"
          build_type="${{ matrix.build_type }}"

          conanfile_hash="${{ hashFiles('conanfile.py') }}"

          # This can be used by to always update a cache entry (useful e.g. for ccache)
          current_date="$(date '+%s')"

          ccache_key_prefix="ccache-$os-$compiler-$compiler_version-$GITHUB_REF-$conanfile_hash-$build_type"

          echo "ccache-key=${ccache_key_prefix}-${current_date}" | tee -a $GITHUB_OUTPUT
          echo "ccache-restore-key=$ccache_key_prefix" | tee -a $GITHUB_OUTPUT

      - name: Restore Conan cache (x86)
        if: matrix.os == 'macos-12' || matrix.os == 'macos-13'
        uses: actions/cache/restore@v4
        with:
          key: ${{ needs.build-conan-deps-x86.outputs.conan-key }}
          path: ${{ env.CONAN_HOME }}/p
          fail-on-cache-miss: true

      - name: Restore Conan cache (arm64)
        if: matrix.os == 'macos-14'
        uses: actions/cache/restore@v4
        with:
          key: ${{ needs.build-conan-deps-arm64.outputs.conan-key }}
          path: ${{ env.CONAN_HOME }}/p
          fail-on-cache-miss: true

      - name: Restore CMake configs (x86; Debug)
        if: matrix.build_type == 'Debug' && (matrix.os == 'macos-12' || matrix.os == 'macos-13')
        uses: actions/cache/restore@v4
        with:
          key: ${{ needs.build-conan-deps-x86.outputs.cmake-prefix-debug-key }}
          path: /tmp/cmake-prefix-dbg.tar
          fail-on-cache-miss: true

      - name: Restore CMake configs (x86; Release)
        if: matrix.build_type == 'Release' && (matrix.os == 'macos-12' || matrix.os == 'macos-13')
        uses: actions/cache/restore@v4
        with:
          key: ${{ needs.build-conan-deps-x86.outputs.cmake-prefix-release-key }}
          path: /tmp/cmake-prefix-dbg.tar
          fail-on-cache-miss: true

      - name: Restore CMake configs (arm64; Debug)
        if: matrix.build_type == 'Debug' && matrix.os == 'macos-14'
        uses: actions/cache/restore@v4
        with:
          key: ${{ needs.build-conan-deps-arm64.outputs.cmake-prefix-debug-key }}
          path: /tmp/cmake-prefix-dbg.tar
          fail-on-cache-miss: true

      - name: Restore CMake configs (arm64; Release)
        if: matrix.build_type == 'Release' && matrix.os == 'macos-14'
        uses: actions/cache/restore@v4
        with:
          key: ${{ needs.build-conan-deps-arm64.outputs.cmake-prefix-release-key }}
          path: /tmp/cmake-prefix-dbg.tar
          fail-on-cache-miss: true

      - name: Restore CMake configs (Release)
        if: matrix.build_type == 'Release'
        uses: actions/cache/restore@v4
        with:
          key: ${{ needs.build-conan-deps.outputs.cmake-prefix-release-key }}
          path: /tmp/cmake-prefix-rel.tar
          fail-on-cache-miss: true

      - name: Extract CMake configs
        run: |
          mkdir conan-env
          tar -xf /tmp/cmake-prefix-*.tar -C conan-env/ --strip-components=1

      - name: Restore Ccache folder
        id: cache-ccache
        uses: actions/cache/restore@v4
        with:
          key: ${{ steps.cache-key.outputs.ccache-restore-key }}
          path: ${{ env.CCACHE_DIR }}

      - name: Reset Ccache stats
        run: ccache --zero-stats

      - name: Configure project
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DCMAKE_PREFIX_PATH="$PWD/conan-env"        \
                -S .                                        \
                -B build

      - name: Build project
        run: cmake --build build -j $(nproc)

      - name: Test project
        run: build/main
